// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Session struct {
	ID          uuid.UUID  `json:"id"`
	Token       string     `json:"token"`
	DeviceID    uuid.UUID  `json:"device_id"`
	Fingerprint string     `json:"fingerprint"`
	IpAddress   string     `json:"ip_address"`
	UserAgent   *string    `json:"user_agent"`
	UserID      *uuid.UUID `json:"user_id"`
	Data        []byte     `json:"data"`
	ExpiresAt   time.Time  `json:"expires_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash []byte    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
