// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const DeleteSessionByID = `-- name: DeleteSessionByID :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSessionByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteSessionByID, id)
	return err
}

const GetSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, token_hash, device_id, user_id, data, expires_at, created_at, updated_at FROM sessions
WHERE token_hash = $1
  AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, GetSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.DeviceID,
		&i.UserID,
		&i.Data,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpsertSession = `-- name: UpsertSession :one
INSERT INTO sessions (id, token_hash, device_id, user_id, data, expires_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE
SET token_hash = EXCLUDED.token_hash,
    device_id = EXCLUDED.device_id,
    user_id = EXCLUDED.user_id,
    data = EXCLUDED.data,
    expires_at = EXCLUDED.expires_at,
    updated_at = EXCLUDED.updated_at
RETURNING id, token_hash, device_id, user_id, data, expires_at, created_at, updated_at
`

type UpsertSessionParams struct {
	ID        uuid.UUID  `json:"id"`
	TokenHash string     `json:"token_hash"`
	DeviceID  uuid.UUID  `json:"device_id"`
	UserID    *uuid.UUID `json:"user_id"`
	Data      []byte     `json:"data"`
	ExpiresAt time.Time  `json:"expires_at"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, UpsertSession,
		arg.ID,
		arg.TokenHash,
		arg.DeviceID,
		arg.UserID,
		arg.Data,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.DeviceID,
		&i.UserID,
		&i.Data,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
