services:
  postgres:
    image: postgres:alpine
    container_name: foundation-basic-db
    environment:
      POSTGRES_USER: foundation
      POSTGRES_PASSWORD: foundation
      POSTGRES_DB: foundation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foundation"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foundation-basic-app
    env_file:
      - .env
    environment:
      PG_CONN_URL: postgres://foundation:foundation@postgres:5432/foundation?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:
