name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # Only run on Go file changes
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

jobs:
  claude-review:
    # Optional: Filter by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4.1)
          # model: "claude-opus-4-1-20250805"
          
          # Direct prompt for automated review (no @claude mention needed)
          direct_prompt: |
            Please review this Go code pull request and provide feedback on:
            - Go idioms and best practices
            - Error handling patterns
            - Concurrency safety (if applicable)
            - Performance considerations
            - Test coverage and quality
            - API design and usability
            - Documentation completeness
            
            Focus on the gokit framework's design principles:
            - Keep the API simple and intuitive
            - Follow Go conventions
            - Ensure type safety with generics
            - Maintain backward compatibility
            
            Be constructive and helpful in your feedback.

          # Optional: Use sticky comments to make Claude reuse the same comment on subsequent pushes to the same PR
          use_sticky_comment: true
          
          # Optional: Add specific tools for running tests or linting
          allowed_tools: "Bash(go test ./...),Bash(go vet ./...),Bash(golangci-lint run)"
          
          # Optional: Skip review for certain conditions
          # if: |
          #   !contains(github.event.pull_request.title, '[skip-review]') &&
          #   !contains(github.event.pull_request.title, '[WIP]')
